services:
  planetary_app_hackathon_mvc:
    image: guledjama97/planetary-app-hackathon-mvc:latest
    build:
      context: ./server
    ports:
      - "80:80"
    restart: always
    depends_on:
      - planetary_app_hackathon_db
    networks:
      - planetary_app_hackathon_network

  planetary_app_hackathon_db:
    image: guledjama97/planetary-app-hackathon-db:latest
    build:
      context: ./db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - planetary_app_hackathon_network

networks:
  planetary_app_hackathon_network:
